
'use server';
/**
 * @fileOverview A Genkit flow to generate a full marketing campaign for a new product.
 *
 * - generateProductCampaign - A function that generates marketing assets for a product.
 * - GenerateProductCampaignInput - The input type for the generateProductCampaign function.
 * - GenerateProductCampaignOutput - The return type for the generateProductCampaign function.
 */

import { ai } from '@/ai/genkit';
import { z } from 'zod';
import { 
  GenerateProductCampaignInputSchema,
  type GenerateProductCampaignInput,
} from '@/app/schemas';


const SocialPostSchema = z.object({
    platform: z.enum(['Twitter', 'LinkedIn', 'Facebook']).describe('The target social media platform.'),
    content: z.string().describe('The generated content for the social media post, tailored to the platform.'),
    hashtags: z.array(z.string()).describe('A list of relevant hashtags for the post.'),
});

const GenerateProductCampaignOutputSchema = z.object({
  socialPosts: z.array(SocialPostSchema).describe('A list of generated social media posts.'),
  marketingImage: z.object({
    prompt: z.string().describe('The prompt used to generate the marketing image.'),
    imageUrl: z.string().url().describe('The data URI of the generated marketing image.'),
  }),
  videoConcept: z.object({
    title: z.string().describe('A catchy title for a short promotional video (e.g., for TikTok or YouTube Shorts).'),
    sceneDescription: z.string().describe('A brief description of the scenes and actions in the video.'),
  }),
});
export type GenerateProductCampaignOutput = z.infer<typeof GenerateProductCampaignOutputSchema>;


export async function generateProductCampaign(input: GenerateProductCampaignInput): Promise<GenerateProductCampaignOutput> {
  return generateProductCampaignFlow(input);
}


const generateProductCampaignPrompt = ai.definePrompt({
    name: 'generateProductCampaignPrompt',
    input: { schema: GenerateProductCampaignInputSchema },
    output: { schema: GenerateProductCampaignOutputSchema },
    prompt: `You are a world-class marketing director for a cutting-edge e-commerce brand.
Your task is to generate a complete set of marketing assets for a new, trending product.

Product Details:
- Name: {{{productName}}}
- Description: {{{description}}}
- Target Audience: {{{targetAudience}}}
- Marketing Angle: {{{marketingAngle}}}

You must generate the following assets:

1.  **Marketing Image**: Create a prompt for an AI image generator to produce a stunning, eye-catching marketing image for this product. The prompt should be descriptive and evoke a powerful emotion or desire related to the product and its marketing angle. The image itself will be generated by a separate tool based on your prompt. For the imageUrl field, you must return the placeholder "data:image/png;base64,IMAGE_DATA_WILL_BE_INSERTED_HERE".

2.  **Promotional Video Concept**: Dream up a short, engaging video concept (5-10 seconds) perfect for platforms like TikTok or Instagram Reels. Provide a title and a scene-by-scene description.

3.  **Social Media Posts**: Generate three distinct social media posts to promote the product, one for each of the following platforms: Twitter, LinkedIn, and Facebook. Tailor the content and tone for each platform and include relevant hashtags.

Return the complete set of assets in the specified JSON format.
`,
});

const generateImageFlow = ai.defineFlow(
  {
    name: 'generateProductImage',
    inputSchema: z.string(), // The prompt for the image
    outputSchema: z.string().url(), // The data URI of the image
  },
  async (prompt) => {
    const { media } = await ai.generate({
      model: 'googleai/imagen-4.0-fast-generate-001',
      prompt: `${prompt}, commercial product photography, vibrant, high-end`,
    });
    if (!media.url) {
      throw new Error('Image generation failed.');
    }
    return media.url;
  }
)

const generateProductCampaignFlow = ai.defineFlow(
  {
    name: 'generateProductCampaignFlow',
    inputSchema: GenerateProductCampaignInputSchema,
    outputSchema: GenerateProductCampaignOutputSchema,
  },
  async (input) => {
    // First, generate the campaign concepts (text, video idea, image prompt)
    const { output: campaignIdeas } = await generateProductCampaignPrompt(input);
    if (!campaignIdeas) {
        throw new Error("Failed to generate campaign ideas.");
    }
    
    // Now, generate the actual image using the prompt from the first step
    const imageUrl = await generateImageFlow(campaignIdeas.marketingImage.prompt);

    // Combine the results
    return {
        ...campaignIdeas,
        marketingImage: {
            ...campaignIdeas.marketingImage,
            imageUrl: imageUrl, // Replace the placeholder with the real image URL
        }
    };
  }
);
