
'use server';
import { config } from 'dotenv';
config();

import '@/ai/flows/classify-inbound-replies.ts';
import '@/ai/flows/convert-speech-to-text.ts';
import '@/ai/flows/convert-text-to-speech.ts';
import '@/ai/flows/generate-social-post.ts';
import '@/ai/flows/interpret-command.ts';
import '@/ai/flows/execute-campaign-action.ts';
import '@/ai/flows/autonomous-lead-gen-flow.ts';
import '@/ai/flows/initiate-outreach-flow.ts';
import '@/ai/flows/answer-self-knowledge-question.ts';
import '@/ai/flows/generate-product-ideas.ts';
import '@/ai/flows/generate-multiple-social-posts.ts';
import '@/ai/flows/generate-app-blueprint.ts';
import '@/ai/flows/generate-site-blueprint.ts';
import '@/ai/flows/generate-product-campaign.ts';
import '@/ai/flows/automated-digital-product-funnel.ts';
import '@/ai/flows/automated-ai-calling-service-funnel.ts';
import '@/ai/flows/generate-feature-marketing-assets.ts';
import '@/ai/flows/answer-customer-query.ts';
import '@/ai/tools/get-omarim-ai-capabilities';
import '@/ai/tools/find-trending-products';
import '@/ai/tools/find-trending-digital-product';
import '@/ai/tools/generate-digital-product';
import '@/ai/tools/get-sales-report';
import '@/ai/tools/get-digital-products-report';
import '@/ai/tools/get-call';
